### ISSUE TITLE
switch from nymag-handlebars to clayhandlebars

### ISSUE THREAD

**Issue by nelsonpecora** [scvodigital/scvo-router#3]
Hi! I noticed you're using `nymag-handlebars`. We just transferred it to our open source organization, so now it lives at https://github.com/clay/handlebars

The current version of `nymag-handlebars` should keep working fine, but if/when you upgrade please don't be alarmed!

**Comment by tonicblue** [comment]
Thanks for this @nelsonpecora , 

This project is still very experimental so we're not really checking the Github much so, sorry I missed your comment. We've updated to your new repo. Thanks for the great set of helpers.
